### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#1]
We'll need to get a website up with basic information as soon as possible to help spread the word about the event. If anyone would be willing to help design the site/or know a designer that would be willing to help that would be much appreciated! We'll have a shoutout somewhere on the site for whoever is willing to do this. I can do the development side.

Here's the wafflejs site for inspiration: https://wafflejs.com

**Comment by visnup** [comment]
The family of websites: brooklynjs.com, manhattanjs.com, jerseyscript.com, peninsulajs.com, borojs.com

**Comment by paulcpederson** [comment]
I'd be willing to do some design on this, and can also do development in terms of front-end (Sass/JS/HTML). Would this be a static site?

**Comment by paulcpederson** [comment]
@emily-plummer let me know what the next steps would be. I have a couple ideas I could just sketch out?

**Comment by emily-plummer** [comment]
Hey @paulcpederson that would be fantastic, thank you so much for offering to help out! A static site should do the trick, we can do all the ticket purchasing on ti.to and just link to it from our homepage. I'd also be down to meet up in person sometime this weekend if you'd like! cc @maxogden

**Comment by paulcpederson** [comment]
Sweet!

**Comment by visnup** [comment]
github pages!

**Comment by visnup** [comment]
aw, now I'm nostalgic for our [old website](https://github.com/wafflejs/wafflejs.github.io/commits/a323c18):
![screen shot 2016-02-01 at 11 18 08 pm](https://cloud.githubusercontent.com/assets/10444/12742397/2e5350fc-c93a-11e5-8386-b788ba14e9b6.png)

**Comment by paulcpederson** [comment]
@visnup emoji timeline!

**Comment by emily-plummer** [comment]
@paulcpederson very much okay with emojis everywhere on the site

**Comment by paulcpederson** [comment]
Hey so did a bit of thinking last night. My thought was that donuts are super interesting visually and my favorite donut in terms of how it looks is pink glazed with sprinkles. I mean you have this subtle rainbow texture over a pink constrained to a perfect circle. It's probably visually one of the most interesting foods of all time. So I figured I'd riff on that and come up with something modern and clean, but also fun and inviting. Here's what I sketched out:

![sprinkles-comp](https://cloud.githubusercontent.com/assets/1031758/12762136/a19c38e0-c9a2-11e5-938f-abf2bd4d1dd4.jpg)

I did a couple other sketches which I could put out there, but I'm just really grooving on this and wanted to get some feedback. 

It also translates amazingly into sticker form:

| Round Sticker | Traditional Hex Sticker |
| ------------------ | ------------------------------- |
| ![donut-js-sprinkles-sticker-circle](https://cloud.githubusercontent.com/assets/1031758/12762209/00eef026-c9a3-11e5-80ad-1da2c109fc05.jpg) | ![donut-js-sprinkles-sticker-hex](https://cloud.githubusercontent.com/assets/1031758/12762212/0a87b69a-c9a3-11e5-9095-8b8408f71302.jpg) |

**Comment by emily-plummer** [comment]
I wholeheartedly agree on the visual prestige of the donut.

😍😍😍 I'm loving these!!! Thank you so much for mocking these up! My only feedback is it would be interesting to see the frosting in a rounder/squiggly shape to make the overall icon look more circular/less boxy. And then maybe we could compare the two? Other than that these look really fun and I'm loving the color scheme. Thanks again!!!

**Comment by paulcpederson** [comment]
@emily-plummer like more drips, so it's more squiggly?

**Comment by visnup** [comment]
procedurally generate the sprinkles for the background every time people come to the site!!

**Comment by paulcpederson** [comment]
Yeah! I was thinking on hover spin the donut in a circle too, lol

**Comment by visnup** [comment]
oooh, spinning donuts is solid.

**Comment by paulcpederson** [comment]
| squarish | squiggley |
| ----------- | ------------- |
| ![sprinkles](https://cloud.githubusercontent.com/assets/1031758/12765661/8f7e75da-c9b4-11e5-906f-0a87e179b668.jpg) | ![squiggley](https://cloud.githubusercontent.com/assets/1031758/12765669/956435f2-c9b4-11e5-973b-2cdb89663706.jpg) |
| ![hex](https://cloud.githubusercontent.com/assets/1031758/12765689/b2dcdda0-c9b4-11e5-9661-9562f79b9215.jpg) | ![donut-js-sprinkles-sticker-hex-squiggley](https://cloud.githubusercontent.com/assets/1031758/12765695/b94ae95c-c9b4-11e5-92b0-67b358b38614.jpg) |
| ![donut-js-sprinkles-sticker-circle](https://cloud.githubusercontent.com/assets/1031758/12765698/be61cb90-c9b4-11e5-8b9f-29c9c02f8805.jpg) | ![donut-js-sprinkles-sticker-circle-squiggley](https://cloud.githubusercontent.com/assets/1031758/12765701/c43f276a-c9b4-11e5-9798-fd1f7ae5cd3d.jpg) |

**Comment by emily-plummer** [comment]
ooooh I really like the squiggly ones!! (pardon my lack of design jargon)

**Comment by paulcpederson** [comment]
whatever, squiggly *is* the official design term!

**Comment by maxogden** [comment]
WOW

**Comment by gastonfig** [comment]
:+1: @paulcpederson. Digging the round stickers. Happy to help with the procedural code if you need a hand.

**Comment by billyroh** [comment]
:stuck_out_tongue: i want these stickers now :doughnut:

**Comment by paulcpederson** [comment]
@gastonfig woooord!!

@emily-plummer do you have the content for the site, or a site outline? We could probably starting figuring out the general layout and styles for the site now.

**Comment by emily-plummer** [comment]
@paulcpederson Yeah I can get some content together this weekend and send it over! I have a rough list here but I can write out content and make an more robust outline. I'm pretty swamped this week but super excited to get the ball rolling!!! https://docs.google.com/spreadsheets/d/1fptsK02kjJAf4uu0wdgBx8meMqvflkErEsnuqCDBeXU/edit#gid=2106527307

**Comment by emily-plummer** [comment]
also: 
![image](https://cloud.githubusercontent.com/assets/8960591/12794351/741a44f8-ca69-11e5-9236-3d18574205bf.png)

lol

Anyone have thoughts on fun domains? https://www.namecheap.com/domains/registration/results.aspx?domain=donutjs.party

**Comment by paulcpederson** [comment]
$700 :(

- $24.88 donut.events
- $32.88 donutjs.io
- $1.88 donutjs.club

**Comment by maxogden** [comment]
donut.wafflejs.com

**Comment by visnup** [comment]
donut.technology

**Comment by emily-plummer** [comment]
Thinking about getting moving on this this week, as we're getting close to nailing down the venue! Anyone have ideas on how the layout of the site should look like? I could whip something together with @paulcpederson 's assets he created but definitely open to suggestions/help building it! @maxogden @paulcpederson @andrewvy

**Comment by paulcpederson** [comment]
@emily-plummer more than happy to pitch in with the front-end stuff (which I think would be all of it because gh-pages?).

**Comment by emily-plummer** [comment]
yes yes no need for a backend! @paulcpederson I'm going to start working on it tomorrow after our meeting with the Cup and Bar people at 3!

**Comment by paulcpederson** [comment]
@emily-plummer I thought the basic layout could be fun donut.js top banner with a big button to get tickets to the next event, then below things like schedule, timeline, etc. Here' a way quick sketch:

![comp](https://cloud.githubusercontent.com/assets/1031758/13404798/47040960-ded0-11e5-8076-122574de899d.jpg)

So the nav at the top of the content wrap becomes sticky to the top after you scroll, and then we stick the logo to the left of the content wrap after you've scroll as well.

For the timeline it would be fun to do a couple more little illustrations. I like how the waffle js folks have a little mascot-like waffle. So here is a sketch of "donny the donut":

![donny](https://cloud.githubusercontent.com/assets/1031758/13404900/d9924684-ded0-11e5-86b5-a4d23ea69b4d.png)

The idea being that he would be singing karaoke, giving js talks, whatever in the schedule timeline. Probably in more of a subdued light gray palette.

**Comment by Fauntleroy** [comment]
I'd love to see the donut itself in hexagon form!

**Comment by emily-plummer** [comment]
@paulcpederson THIS IS SO GREAT. Thanks so much for mocking this up I love it!!!

**Comment by paulcpederson** [comment]
@emily-plummer I'm honestly shocked how down you are with my weird ideas :smile:

**Comment by emily-plummer** [comment]
@paulcpederson the weirder the better! #keepjsweird

**Comment by paulcpederson** [comment]
#makejsweirdagain

**Comment by visnup** [comment]
😂

**Comment by visnup** [comment]
is that a sword that donny has in the middle of the timeline?

**Comment by visnup** [comment]
small suggestion for donny: have you tried rounder, donut-hole-like hands for him?

**Comment by emily-plummer** [comment]
@visnup it's a karaoke microphone but I think we could have a sword fighting section of the event as well

**Comment by maxogden** [comment]
in donny we trust

<img width="495" alt="screen shot 2016-02-29 at 11 15 43 am" src="https://cloud.githubusercontent.com/assets/39759/13405941/cdc6ec88-ded5-11e5-9f88-f9a87cfe5d02.png">

**Comment by emily-plummer** [comment]
@paulcpederson do you mind sending me the sketch/illustrator file for the donut stickers? I'm gunna get some ordered :)

**Comment by paulcpederson** [comment]
for sure, one sec

**Comment by paulcpederson** [comment]
@emily-plummer sorry that took a second: http://cl.ly/2q2j1516403Q/donut.js.zip

**Comment by emily-plummer** [comment]
@paulcpederson thanks!

**Comment by emily-plummer** [comment]
@paulcpederson the internet really likes your branding: https://twitter.com/kosamari/status/704768850018095104

**Comment by jden** [comment]
I like your branding, too! I'll tryn grab a donut sticker next time I'm in down.

**Comment by paulcpederson** [comment]
![bowing_penguin](https://cloud.githubusercontent.com/assets/1031758/13442984/b80b56ac-dfb3-11e5-911b-f8e95a45fdd1.gif)

**Comment by emily-plummer** [comment]
check it out [donutjs.club](url)

**Comment by emily-plummer** [comment]
Just pushed some more changes! It would feel really great to get a mock schedule up soon, though I'm not totally sure where to go with that so if anyone has ideas feel free to grab that!

**Comment by paulcpederson** [comment]
@emily-plummer I just forked the repo so if you want I could take a pass at this stuff and open a pr! (ie. knowing the font, and adding like a fake schedule with some sweet donut illustrations).

**Comment by emily-plummer** [comment]
@paulcpederson awesome sounds good! I made a few updates yesterday so you might want to pull in again! I made a little schedule-thing but def feel free to do whatever you want to it! I am not attached to it whatsoever :)
![image](https://cloud.githubusercontent.com/assets/8960591/13505451/12615a72-e12e-11e5-9f61-98628c7bfed8.png)

**Comment by paulcpederson** [comment]
cool! I'll try to get some stuff set up in there.

**Comment by paulcpederson** [comment]
@emily-plummer ok I got this looking pretty...pretty...pretty..good in https://github.com/donut-js/donut-js.github.io/pull/10 let me know what you think!

**Comment by paulcpederson** [comment]
since there is a pretty cool website now should we close this?

**Comment by emily-plummer** [comment]
yes!
