### ISSUE TITLE
May Call for Speakers

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#14]
We're looking for speakers for our may meetup!

How do I submit a talk?
You can either comment on this issue or send us an email.

When/where is it
May 31st, at 6:30 at Cup and Bar! But if we get too many proposals and we really love your talk, we'd be happy to schedule you for a later month!

What should I talk about?
We don’t have a strict formula, but this is the balance we try to strike every month:

2x Creative Talks: Creative applications of programming. Such as: generating lego murals out of static images, and building an in-browser RPG, generative art, etc.

1x Passion Talk: Something you’re excited about outside of work. This can literally be anything! Kittens, mental health, how much you love burritos.

1x Technical Talk: A deep dive on a technical topic!

Do I need to be an expert to talk?
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply!

How long should my talk be?
Ten minutes. There won't be any formal Q&A.

What should be in my talk submission?
Just a few sentences describing what you want to talk about would be great.

**Comment by emily-plummer** [comment]
Carrying some comments over from the April thread:

@doodles526 mentioned: "For either May or June I would be down for giving a talk on building turn-key High Availability Postgresql using etcd if there's interest and still room on the ballot!"

**Comment by emily-plummer** [comment]
We'll also be having @toddself give a talk on hiring/interviewing practices!

**Comment by samjulien** [comment]
Hi! Lately I've been using a combination of socket.io, johnny-five, and RxJS to read and maniupulate data from an Arduino, like visualize it or generate audio. I'd be happy to give a talk about that stuff - like how I've been making a theremin with light sensors that produces sin waves controlled by observables in RxJS. Would that fit in the creative category? Thanks for your consideration - looking forward to the meeting in April! :smile:

**Comment by nickurban** [comment]
I'd be interested in giving a passion talk about meditation, common misconceptions, and how it is so beneficial (not for the reason people might think). 

I would also be interested in giving a technical talk on "Elixir / Phoenix - familiar, but different. A Rails developer's perspective".

**Comment by TeffenEllis** [comment]
@emily-plummer I'd like to give a talk about interactive novel I'm making in JavaScript. It's about love across universes, and making your own destiny.

<img src="http://i.imgur.com/VCLBtzU.gif" />

Cheers.

**Comment by jden** [comment]
Based on the pitch-with-gif, I am interested in seeing @TeffenEllis's talk

**Comment by segdeha** [comment]
I'd love to give a passion talk about how companies can better support junior developers (based on my Medium article of the same topic: https://medium.com/@segdeha/on-code-schools-the-plight-of-the-junior-developer-9c3363f08902)

**Comment by emily-plummer** [comment]
YES YES YES!  ❤️ I would really love to see a talk about this @segdeha!!! Totally my bad here (I should have closed this issue), but we've closed submissions for May and have a new process for submitting talks - if you don't mind, could you submit your talk via this form? http://donutjs.club/submit-talk/ We'll be selecting talks for June around the first week of June! 😸
