### ISSUE TITLE
I feel like DonutJS folks need to know about and bum rush this sale

### ISSUE THREAD

**Issue by jwithington** [donut-js/donut-js.github.io#26]
I did a double take, wondering if [this donut shirt was made by y'all](https://cottonbureau.com/products/donut-share).

Not currently going to print!

![image of donut shirt](https://cottonbureau.imgix.net/products/originals/9707_6IU2.png)

**Comment by jden** [comment]
oh man, I'm all about https://cottonbureau.com/products/donut-tread-on-me

**Comment by obensource** [comment]
@jwithington that's AMAZING!

**Comment by jwithington** [comment]
@obensource but it hasn't sold enough to go to print!

:sob:
