### ISSUE TITLE
'Video' section for donutjs.club

### ISSUE THREAD

**Issue by obensource** [donut-js/donut-js.github.io#28]
We should probably have a link next to 'Home' on the landing page linking to videos from previous meetups.

**Comment by obensource** [comment]
I'll just put in a PR with that super soon.

**Comment by aaronpk** [comment]
Bump! I'm starting to get quite a collection of past videos to include!

**Comment by matthewmcvickar** [comment]
This is finally up! http://donutjs.club/past-speakers/
