### ISSUE TITLE
Create an animated logo screen for videos

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donut-js.github.io#29]
Hey there! I'm looking forward to recording the talks tonight! Could someone throw together a page on the site that I can use as a title screen for the videos? I'm thinking basically the animated background of the site with a large centered "Donut JS" title and logo. I just need it up at a URL and I can screencap it from there! 🎉

**Comment by paulcpederson** [comment]
@aaronpk I can probably do this. When do you need it? By tonight?

**Comment by aaronpk** [comment]
I probably won't have time to cut the videos until next week, so no rush. Unless we're livestreaming tonight, in which case yes.

**Comment by aaronpk** [comment]
@paulcpederson bump! I'm planning on finishing the videos this weekend!

**Comment by jden** [comment]
does running `document.querySelector('.constrain').remove()` in a javascript console on the homepage work for you?

**Comment by matthewmcvickar** [comment]
@aaronpk @paulcpederson @jden Thank you for your ideas and input on this, and I'm very sorry for the delay. Here is a special ‘splash screen’ with just the logo and sprinkles, as requested: http://donutjs.club/splash/

**Comment by aaronpk** [comment]
Thanks! This will be great for the videos as well as for the live events!
