### ISSUE TITLE
make donny eat hotdogs + other BBQ'y things

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#34]
Hey there! I was thinking it would be nice to have some BBQ themed graphics for our upcoming Donut.js BBQ

@paulcpederson originally crafted Donny, but anyone is welcome to riff on this! I can send over AI files for Donny 😄

**Comment by paulcpederson** [comment]
oh so down! like what are we thinking like Donny with a chefs hat holding a big grill spatula thing?

**Comment by paulcpederson** [comment]
![](http://f.cl.ly/items/0e333O2S1M1h0c3P052m/donny-bbq-svg.svg)
.ai and .svg of donny roasting a hot dog here:
http://cl.ly/101F2k0Z3l1y/Archive%202016-06-30%20at%2011.51.51%20AM.zip

**Comment by jden** [comment]
:squee:

**Comment by emily-plummer** [comment]
omg this is amazing @paulcpederson!!!!
