### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#4]
Right now we are discussing having the event at Cup and Bar!

**Comment by emily-plummer** [comment]
We've locked down Cup and Bar! http://giphy.com/gifs/dancing-dance-party-clubbing-blSTtZehjAZ8I

**Comment by obensource** [comment]
I'm pretty good friends with Justin Harn (Director of Programs and Community Engagement at Hollywood Theater), and depending on which way we want this to swing I can definitely get the conversation going about the possibility of doing this monthly at the Hollywood? To me, this almost seems like a perfect fit given the interests of this group and the theater. It would be cool to get @emily-plummer and @maxogden in on that conversation if we'd want to meet up with him.

**Comment by emily-plummer** [comment]
@obensource Unless something falls through, I think we're pretty set on Cup and Bar at this point! We've already discussed the details with George about using the space and set up some dates with them on their calendar! We'll def keep Hollywood Theater in mind tho if anything falls through! :)

**Comment by obensource** [comment]
@emily-plummer totally. Cup and Bar seems to makes more sense the more I've understood the collective push towards where Donut.js is going. The connected-ness that happens more naturally in an open environment like C&B is harder to get in a theater where people are sectioned off by seat rows and speakers are elevated above them on a big stage. I'm super stoked we're going to meet in a place where we're 'all on the same level'. 🙌
