### ISSUE TITLE
Add videos from past talks

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#44]
Add an embedded video for each of the past talks at donutjs.club/past-speakers

videos here: https://www.youtube.com/watch?v=rdG8CLMdEeM&list=PLRyLn6THA5wOw7Xm7df_F4sutkIi1OECF

**Comment by aaronpk** [comment]
Here's the three playlists:

* [May](https://www.youtube.com/playlist?list=PLRyLn6THA5wNtEN0tKntdxdb3Ctb-Cg2x)
* [June](https://www.youtube.com/playlist?list=PLRyLn6THA5wPlq5gphSOAdRZASuFRrfW7)
* [September](https://www.youtube.com/playlist?list=PLRyLn6THA5wPegsjRJU_q2B7vze3yZRjZ)

**Comment by jwithington** [comment]
working on this now 🍩

**Comment by matthewmcvickar** [comment]
This is done now! We should create a more visible link to the past speakers and videos, too.

**Comment by matthewmcvickar** [comment]
http://donutjs.club/past-speakers/
