### ISSUE TITLE
Design for Front Window Poster! 

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#46]
We need to come up with a design to use for a poster to put in the front window of the Ace Hotel during our event!

My idea for it would be something like:
- Blue background with sprinkles
- "Donut.js" with the donut underneath it
- underneath that the words "a donut themed event for the js community" or something like that that briefly describes the event for passerbys

If anyone is willing to jump on this it would be much appreciated! I don't have AI or Sketch on my laptop 😭 Feel free to have fun with it, that's just my preliminary idea!

**Comment by paulcpederson** [comment]
@emily-plummer I can probably help. 😄

**Comment by emily-plummer** [comment]
yasss @paulcpederson you da best!

**Comment by paulcpederson** [comment]
@emily-plummer what size are you thinking?

**Comment by paulcpederson** [comment]
Ok, I took a stab at this. I made it 24"x32" as that is a pretty typical poster size, but I can change the size if that's too big.

View/Download:
[poster.pdf](https://github.com/donut-js/donut-js.github.io/files/531957/poster.pdf)

**Comment by matthewmcvickar** [comment]
Thank you so much Paul!! This looks **awesome**!

One grammar note: 'donut themed' should be 'donut-themed' (add a hyphen).

And I think the description is still too vague for someone who doesn't already know what the JS community is. How about something like: "a night of donuts and talks at the corner of code and creativity"

**Comment by paulcpederson** [comment]
@matthewmcvickar cool. Here is a version with new copy:

[poster2.pdf](https://github.com/donut-js/donut-js.github.io/files/534050/poster2.pdf)

**Comment by emily-plummer** [comment]
PAUL IS DA BEST

**Comment by emily-plummer** [comment]
This looks great!

**Comment by emily-plummer** [comment]
just ordered the poster from costco! It will be at the next event! Thanks paul!

**Comment by paulcpederson** [comment]
woot woot! 🎉
