### ISSUE TITLE
add November videos

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donut-js.github.io#54]
Here's the playlist: https://www.youtube.com/watch?v=c9lFkejg-o8&list=PLclEcT4yxER5DWdcPnIij8ur7tQv9mkxG

and individual videos:

* https://www.youtube.com/watch?v=c9lFkejg-o8&index=1&list=PLclEcT4yxER5DWdcPnIij8ur7tQv9mkxG
* https://www.youtube.com/watch?v=nsYEyI7V4Vk&index=2&list=PLclEcT4yxER5DWdcPnIij8ur7tQv9mkxG
* https://www.youtube.com/watch?v=5PakA8zM51o&index=3&list=PLclEcT4yxER5DWdcPnIij8ur7tQv9mkxG
* https://www.youtube.com/watch?v=6JajwlNebP4&index=4&list=PLclEcT4yxER5DWdcPnIij8ur7tQv9mkxG

**Comment by matthewmcvickar** [comment]
Done, done, done, and done!
