### ISSUE TITLE
more video links

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donut-js.github.io#77]
These still say coming soon on the website:

* June 2019 https://www.youtube.com/playlist?list=PLclEcT4yxER75WBIf3-1qxO1Kuc0OAi-1
* August 2019 https://www.youtube.com/playlist?list=PLclEcT4yxER6MT3tioOrWfNfJvDrjP0ts
* January 2020 https://www.youtube.com/playlist?list=PLclEcT4yxER7Y1F5OAJ_NYb_cPFqYXAMq

**Comment by matthewmcvickar** [comment]
Closed via https://github.com/donutjs/donutjs.club/commit/9ada854cf35aec5afc1c874bf2078f8a9319f3bc. Thank you @aaronpk! I think the only missing videos at this point are [November 2019](https://donutjs.club/past-speakers/#november-2019), and I can't remember what happened with those… is that a month where I messed up the A/V? 😅
