### ISSUE TITLE
April Call for Speakers

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donut-js.github.io#8]
We're looking for speakers for our meetup!

**How do I submit a talk?**
You can either comment on this issue or send us an <a href='mailto:hello@donutjs.club'>email</a>.

**When/where is it**
April 26th, at 6:30 at Cup and Bar! But if we get too many proposals and we really love your talk, we'd be happy to schedule you for a later month!

**What should I talk about?**
We don’t have a strict formula, but this is the balance we try to strike every month:

**2x Creative Talks:** Creative applications of programming. Such as: generating lego murals out of static images, and building an in-browser RPG, generative art, etc.

**1x Passion Talk:** Something you’re excited about outside of work. This can literally be anything! Kittens, mental health, how much you love burritos.

**1x Technical Talk:** A deep dive on a technical topic!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply!

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**Comment by visnup** [comment]
Ooh, I want to give a talk on "HSL -- the RGB you've been waiting for." I prepared it for peninsulajs but that so far has fallen through. It's short and interactive and about what HSL and color spaces are and why you should be using HSL instead of RGB in development. Slides/incomplete blog post is at visnup.github.io/hsl.

**Comment by emily-plummer** [comment]
@visnup I was *just* about to ask you if you wanted to give a talk!

**Comment by obensource** [comment]
I'd love to give a talk on *"Remote-performing––it's a thing!"*

This talk would give a little detail about how the Web Audio and Web MIDI APIs can be used in tandem with WebRTC DataChannels to make remote musical collaborations and performances happen in realtime. It would be closed with a fun musical performance given by a remote player and myself.

**Comment by visnup** [comment]
@emily-plummer would love to! I can pitch a bunch of other ideas too if the HSL one sounds boring.

**Comment by toddself** [comment]
I would love to talk about testing. Not necessarily why we test but like how to test --  getting browser testing set up, what to test, how to know what you are testing, etx.

**Comment by toddself** [comment]
Also would love to talk about how we can all work together to make hiring and interviewing a better process. I gave a talk at queensjs about this last spring and would love to elaborate further on it!

**Comment by visnup** [comment]
thought of another talk: I want to go down this list of things https://en.wikipedia.org/wiki/Timeline_of_the_far_future and talk about how crazy everything on that list is.

**Comment by feministy** [comment]
yay waffles/donuts! i'm so glad this is coming to portland. i'd love to give a talk!

probably would fall under creative: i've done a lot of work lately on auto-magically generating knitting patterns. taking something real-world and math-based and turning into a program is actually super easy (no one is surprised here), but when you combine that with best practices and expected conventions, things get a little tricky... especially when your output will result in *lots* of manual hours creating a real object :grimacing: 

let me know if you need more details than that and i am happy to provide them. also let me know if this doesn't sound interesting so i can make sure to buy a ticket asap!! :smile:

**Comment by emily-plummer** [comment]
@feministy @visnup @toddself @obensource Hey everyone! Sorry for the late reply, I've been out of the country with pretty bad wifi all week! First of all, thanks SO SO much for submitting talk proposals! They are all really great and sounds like perfect talks for DonutJS :smile_cat: :smile_cat: I'm planning on syncing up with @maxogden early next week so we can get back to everyone soon but I just wanted to let everyone know that these are all great ideas and we'll get in touch shortly :) :+1:

**Comment by emily-plummer** [comment]
Hey all! We've chatted and come up with the lineup, here's what we're thinking:

**April:**
@visnup : "HSL -- the RGB you've been waiting for" 
@feministy : Auto-generating knitting patterns
@obensource : "Remote-performing––it's a thing!"
Stef Hatcher: Improving accessibility in single page apps

**May:**
@toddself : Improving hiring/interviewing practices

If you haven't come up with a official title yet, or want to have something listed other than what's up here, let me know! Also - can each of you send me a whatever link you'd like your name to link to on our site? We'll update the site soon! :smile_cat: 

**That being said! If you're new to this thread and want to give a talk, please still reach out! We can book you for May/June :)**

**Comment by obensource** [comment]
@emily-plummer 🙌wahoo! 🙌SO STOKED! 🙌

**Comment by emily-plummer** [comment]
Also, if you're a selected speaker for April, make sure not to buy a ticket! Tickets are obvs covered if you're speaking :) :)

**Comment by emily-plummer** [comment]
Schedule is live: http://donutjs.club/#schedule

I'm going to wait a bit to announce it on twitter but let me know if there's anything you'd like me to change! :)

**Comment by obensource** [comment]
@emily-plummer :+1: :+1: :+1:

**Comment by feministy** [comment]
YAYYY!!!! 

For a title... I will come up with something quippy and send it over!

**Comment by stefhatcher** [comment]
Yay! Super excited!

**Comment by doodles526** [comment]
For either May or June I would be down for giving a talk on building turn-key High Availability Postgresql using etcd if there's interest and still room on the ballot!
